CREATE TABLE [dbo].[SSB_MES2LC]
(
[Rowid] [int] NOT NULL IDENTITY(1, 1),
[OrderPk] [int] NOT NULL,
[OrderID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SKU] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TruckID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[StopLocationID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[UnitSize] [int] NOT NULL,
[MLength] [decimal] (7, 3) NOT NULL,
[MWidth] [decimal] (7, 3) NOT NULL,
[CoreType] [bit] NOT NULL,
[BorderType] [int] NOT NULL,
[BoxPkg] [bit] NOT NULL,
[NoofMULayers] [int] NOT NULL,
[CoreHeight] [decimal] (7, 3) NOT NULL,
[L1Height] [decimal] (7, 3) NOT NULL,
[L1Pattern] [int] NOT NULL,
[L1Type] [int] NOT NULL,
[L2Height] [decimal] (7, 3) NOT NULL,
[L2Pattern] [int] NOT NULL,
[L2Type] [int] NOT NULL,
[L3Height] [decimal] (7, 3) NOT NULL,
[L3Pattern] [int] NOT NULL,
[L3Type] [int] NOT NULL,
[L4Height] [decimal] (7, 3) NOT NULL,
[L4Pattern] [int] NOT NULL,
[L4Type] [int] NOT NULL,
[L5Height] [decimal] (7, 3) NOT NULL,
[L5Pattern] [int] NOT NULL,
[L5Type] [int] NOT NULL,
[L6Height] [decimal] (7, 3) NOT NULL,
[L6Pattern] [int] NOT NULL,
[L6Type] [int] NOT NULL,
[BFHeight] [decimal] (7, 3) NOT NULL,
[ERWidth] [decimal] (7, 3) NOT NULL,
[SRWidth] [decimal] (7, 3) NOT NULL,
[SRDesign] [bit] NOT NULL,
[ERDesign] [bit] NOT NULL,
[RailHeight] [decimal] (7, 3) NOT NULL,
[ContactArea] [bit] NOT NULL,
[RailDensity] [bit] NOT NULL,
[RowCount] [int] NOT NULL,
[CoilStyle] [int] NOT NULL,
[CoilDia] [decimal] (7, 3) NOT NULL,
[ColumnCount] [int] NOT NULL,
[CoilCount] [int] NOT NULL,
[FECSAPNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSAPDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSAItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSAQty] [decimal] (7, 3) NULL,
[FECSAQtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSRPNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSRPDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSRItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSRQty] [decimal] (7, 3) NULL,
[FECSRQtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECSRPL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECERPNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECERPDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECERItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECERQty] [decimal] (7, 3) NULL,
[FECERQtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECERPL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECBFPNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECBFPDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECBFItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECBFQty] [decimal] (7, 3) NULL,
[FECBFQtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FECBFPL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MUSAPNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUSAPDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUSAItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUSAQty] [decimal] (7, 3) NULL,
[MUSAQtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL1PNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL1PDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL1ItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL1Qty] [decimal] (7, 3) NULL,
[MUL1QtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL1PL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MUL2PNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL2PDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL2ItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL2Qty] [decimal] (7, 3) NULL,
[MUL2QtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL2PL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MUL3PNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL3PDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL3ItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL3Qty] [decimal] (7, 3) NULL,
[MUL3QtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL3PL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MUL4PNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL4PDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL4ItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL4Qty] [decimal] (7, 3) NULL,
[MUL4QtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL4PL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MUL5PNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL5PDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL5ItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL5Qty] [decimal] (7, 3) NULL,
[MUL5QtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL5PL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[MUL6PNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL6PDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL6ItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL6Qty] [decimal] (7, 3) NULL,
[MUL6QtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MUL6PL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PCASAPNO] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCASAPDesc] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCASAItemClass] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PCASAQty] [decimal] (7, 3) NULL,
[PCASAQtyUoM] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PL] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BFLength] [decimal] (7, 3) NULL,
[BFWidth] [decimal] (7, 3) NULL,
[Seq] [int] NULL,
[PQ] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DueDate] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DueTime] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstDataTime] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SSB_MES2LC] ADD CONSTRAINT [PK_SSB_MES2LC] PRIMARY KEY CLUSTERED  ([Rowid]) ON [PRIMARY]
GO
