CREATE TABLE [dbo].[PLC_DYN_SpL01]
(
[RowID] [int] NOT NULL IDENTITY(1, 1),
[JobID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitSize] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Length] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Width] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BFThick] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BFLOC] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SRThick] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ERThick] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RailHeight] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoilDia] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NoOfRows] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RowCount] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoilStyle] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoreHeight] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MULayers] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L1Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L1Thickness] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L1Loc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2Thickness] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2Loc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3Thickness] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3Loc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4Thickness] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4Loc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5Thickness] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5Loc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L6Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L6Thickness] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L6Loc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PillowTop] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoilLoc] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TruckID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BoxRequired] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StopID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCover] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SKUNo] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MLength] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MWidth] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CoilType] [nvarchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L2PNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L1PNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L6PNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L5PNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L4PNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[L3PNo] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BFPno] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EstSeq] [int] NULL,
[FECType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
